server:
  port: 8080
  servlet:
    context-path: /phongtro

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/RentalDB"
    username: root
    password: 251123

jwt:
  signerKey: "WRT8OnU7TeWE0R/DLuS9BrvYV9hVSfAt1Co5ZWXkG3KRYajL8FpjsuVYoE0eVWw9"

file:
  uploadDir: "C:/DoAnTotNghiep/UploadMedia"


